language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

dist: xenial

install:
  - pip install pytest flake8
  - python setup.py install

script:
  - flake8 yumemi
  - pytest tests

deploy:
  provider: pypi
  user: fpob
  password:
    secure: AO2v+515yEolV6reqX8unW6pvB+92c+u9oT69NQjwuWStYvAzxJdIgcAJdHT3FTc9vFegVwapCDAWRrqxS+zW+Vajvvux+NSn5cYPDAouZz5oy9g9jATwSaKdPXqQAqneNQt8DEJC2UH2Exjd0grsgDY8D/ZNlIc4n8PFY2jJDgdlk5p2yQZ8ysoSGwy1EHSNBDWTvezjTL4eBoehsLoR+iop2dF0HOZ1w4WxVkIQlv3xS+qOZ+BzuCNv54vpSd0+tzrjfupsv/It55vbiXMolKAiVWuA7mT2PzdSLDOB9OYVLIw7iFioWeH+Kdxea7ulKJ43cWgceTQKD9fCokzvPLe4dZi9xznj1JpigBMinAPUeFZXuue79bgFXRPBO1mmX1yLAq5Xd9AWivvnXD8JsfDUx8JdRrZydQu/xvrsFEMAT2QgWsD9K5/+Bmv46Vh4VMCKDvc8SOfO4nO5BAlgoE2VnGqpdGewuN5ZqVTbu2flW3p+OsvnAU1RYYgDAwcSrcnBLSDgRv3j+/Ob3g1Oh4pw+Yv5znrPSB7sxiB02u2FgMJkhlnwk067zR/WMG5e0PZNOX/RfwJYvBShjPeacVChUA307rEou+xfQYQ/Q/qfw9v8ZVVCptdZEh50mJn1xzZTmg+Bga7mV5XvaYJVm1nIkE2mBm0y+6CZZHGbeY=
  on:
    tags: true
    python: "3.6"
